stages:
  - deploy

variables:
  SERVER_USER: xuantruong
  SERVER_IP: "34.124.150.245"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  PROJECT_PATH: "/data/cwgame-be"

before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

deploy_dev:
  stage: deploy
  script:
    - |
      ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
        cd $PROJECT_PATH && \
        git pull origin dev && \
        docker-compose down && \
        docker-compose up --build -d
      "
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
      when: always
    - if: $CI_COMMIT_BRANCH == "dev"
      when: always
  environment:
    name: development

deploy_prod:
  stage: deploy
  script:
    - |
      ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
        cd $PROJECT_PATH && \
        git pull origin main && \
        docker-compose down && \
        docker-compose up --build -d
      "
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: always
    # - if: $CI_COMMIT_BRANCH == "main" # Don't deploy from direct commit
    #   when: always
  environment:
    name: production