export const RPC_PACKAGE_NAME = 'cwgame_api';

export enum EGrpcService {
	CW_GAME_SERVICE = 'CwGameService',
	WALLET_SERVICE = 'WalletService',
	CHARACTER_SERVICE = 'CharacterService',
	INVENTORY_SERVICE = 'InventoryService',
	MARKETPLACE_SERVICE = 'MarketplaceService',
	BATTLE_SERVICE = 'BattleService',
	FARMING_SERVICE = 'FarmingService',
	SOCIAL_SERVICE = 'SocialService',
	SHOP_SERVICE = 'ShopService',
	GAME_SYSTEM_SERVICE = 'GameSystemService',
}

export const GRPC_METHODS = {
	[EGrpcService.CW_GAME_SERVICE]: {
		SyncAccount: 'SyncAccount',
		SayHello: 'SayHello',
		UpdateAccount: 'UpdateAccount',
		GetAccountByUsername: 'GetAccountByUsername',
		RegisterAccount: 'RegisterAccount',
		AuthenticateAccount: 'AuthenticateAccount',
		GetProfile: 'GetProfile',
		GetGlobalUserRanking: 'GetGlobalUserRanking',
		GetGlobalLandRanking: 'GetGlobalLandRanking',
		GetChestInfo: 'GetChestInfo',
		GetCwUserIdByNkUserId: 'GetCwUserIdByNkUserId',
	},
	[EGrpcService.WALLET_SERVICE]: {
		GetUserWallets: 'GetUserWallets',
		AddCurrency: 'AddCurrency',
		SpendCurrency: 'SpendCurrency',
	},
	[EGrpcService.CHARACTER_SERVICE]: {
		ListCharacters: 'ListCharacters',
		GetCharacter: 'GetCharacter',
		UpdateCharacter: 'UpdateCharacter',
		EquipItem: 'EquipItem',
		UnequipItem: 'UnequipItem',
		FeedCharacter: 'FeedCharacter',
		UnlockSkillSlot: 'UnlockSkillSlot',
		SetDefaultCharacter: 'SetDefaultCharacter',
		LevelUpCharacter: 'LevelUpCharacter',
		UpgradeCharacterStats: 'UpgradeCharacterStats',
	},
	[EGrpcService.SHOP_SERVICE]: {
		ListShopItems: 'ListShopItems',
		BuyShopItem: 'BuyShopItem',
		AddItemToShop: 'AddItemToShop',
		AddToWishlist: 'AddToWishlist',
		RemoveFromWishlist: 'RemoveFromWishlist',
		ListMarketTradeItems: 'ListMarketTradeItems',
		SellMarketTradeItem: 'SellMarketTradeItem',
		BuyMarketTradeItem: 'BuyMarketTradeItem',
		CancelMarketTradeItem: 'CancelMarketTradeItem',
	},
	[EGrpcService.INVENTORY_SERVICE]: {
		GetUserInventory: 'GetUserInventory',
		AddItemToInventory: 'AddItemToInventory',
		RemoveItemFromInventory: 'RemoveItemFromInventory',
		GetUserInventoryCurrency: 'GetUserInventoryCurrency',
		SellItem: 'SellItem',
	},
	[EGrpcService.GAME_SYSTEM_SERVICE]: {
		GetEggSystemConfig: 'GetEggSystemConfig',
		CraftEgg: 'CraftEgg',
		OpenItem: 'OpenItem',
		GetGameSystemConfig: 'GetGameSystemConfig',
		ClaimChest: 'ClaimChest',
	},
	[EGrpcService.BATTLE_SERVICE]: {
		GetBattlePvEInfo: 'GetBattlePvEInfo',
		GetBattlePvpInfo: 'GetBattlePvpInfo',
		BattlePve: 'BattlePve',
		BattlePvp: 'BattlePvp',
		GetBattleHistory: 'GetBattleHistory',
	},
	[EGrpcService.FARMING_SERVICE]: {
		GetLandInfo: 'GetLandInfo',
		HarvestLand: 'HarvestLand',
		LevelUpLand: 'LevelUpLand',
		LandInteraction: 'LandInteraction',
	},
};
